# Generated by Django 5.2.3 on 2025-06-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('country_flag', models.URLField(blank=True, null=True, verbose_name='Country Flag URL')),
                ('country_currency', models.CharField(max_length=10, verbose_name='Country Currency Code (e.g., USD, IDR)')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=150, verbose_name='Category Title')),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Kilo (International)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.country', verbose_name='Origin Country')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['country__country_name', 'category_title'],
                'unique_together': {('country', 'category_title')},
            },
        ),
    ]
